# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-22 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='Phome',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
