# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-11 15:03
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_image'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('Dhaka', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='Phone',
            new_name='phone',
        ),
    ]
